config/routes.rb
Rails.application.routes.draw do
  get 'notes', to: 'notes#index', as: 'notes'

  get 'notes/new'

  post 'notes', to: 'notes#create'

  get 'notes/:id', to: 'notes#show', as: 'note'

  get 'notes/:id/edit', to: 'notes#edit', as: 'edit_note'

  patch 'notes/:id', to: 'notes#update'

  delete 'notes/:id', to: 'notes#destroy'

  root 'notes#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to @note, notice: 'note was successfully created.'
    else
      render :new
    end
  end

  def show
    @note = Note.find(params[:id])
  end

  def edit
    @note = Note.find(params[:id])
  end

  def update
    @note = Note.find(params[:id])

    if @note.update(note_params)
      redirect_to @note, notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    redirect_to notes_url, notice: 'Note was successfully destroyed.'
  end

  private
    def note_params
      params.require(:note).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minievernote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<div class="edit-notes-page">
  <%= form_for @note do |form| %>
    <div>
      <%= form.text_field :title, class: 'form-note__title', placeholder: '제목' %>
    </div>

    <div>
      <%= form.text_area :body, class: 'form-note__body', placeholder: '내용' %>
    </div>

    <%= form.submit  %>
    <a href="/notes/<%= @note.id %>">취소</a>
  <% end %>
</div>

app/views/notes/index.html.erb
<div class="notes-page">
  <h1>MINI EVERNOTE</h1>
  <% @notes.each do | note | %>
    <a href="/notes/<%= note.id %>">
      <div class="note">
        <h3 class="note__title">
          <%= note.title %>
        </h3>
        <p class="note__body">
          <%= note.body %>
        </p>
      </div>
    </a>
  <% end %>

  <a href="/notes/new"><i class="fa fa-plus-circle fa-2x" aria-hidden="true"></i></a>
</div>

app/views/notes/new.html.erb
<div class="new-notes-page">
<%= form_for @note do |form| %>
  <div>
    <%= form.text_field :title, class: 'form-note__title', placeholder: '제목' %>
  </div>

  <div>
    <%= form.text_area :body, class: 'form-note__body', placeholder: '내용' %>
  </div>

  <%= form.submit  %>
  <a href="/notes">취소</a>
<% end %>
</div>

app/views/notes/show.html.erb
<div class="show-notes-page">
  <a href="/notes"><-</a>

  <div class="note">
    <h1 class="note__tittle"><%= @note.title %></h1>
    <p class="note__body">
      <%= @note.body %>
    </p>
  </div>

  <%= link_to "수정", edit_note_path(@note) %>
  <%= link_to "삭제", @note, :method => :delete, data: { confirm: '정말 삭제하시겠습니까?' }%>
</div>